version: "3"
services:
  
  mongodb:
    build: 
      dockerfile: mongodb.Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: this-is-totally-a-docker-secret
      MONGO_INITDB_DATABASE: devops-challenge-db
    ports: 
      - 27017:27017
  
  application:
    build: 
      dockerfile: application.Dockerfile
    environment:
      - MONGO_URI=mongodb://devopsC:dev0psUs3r@mongodb:27017/devops-challenge-db
    ports:
      - 8080:8080
    