apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    created.by: Jason Verde
  labels:
    purpose: application
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: application
  strategy: {}
  template:
    metadata:
      labels:
        purpose: application
    spec:
      containers:
        - env:
            - name: MONGO_URI
              value: mongodb://devopsC:dev0psUs3r@mongodb:27017/devops-challenge-db
          image: thecatismaybe/public:application
          name: application
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
