apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    purpose: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: mongodb
  strategy: {}
  template:
    metadata:
      labels:
        purpose: mongodb
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: devops-challenge-db
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: this-is-totally-a-docker-secret
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: thecatismaybe/public:mongodb
          name: mongodb
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
