apiVersion: v1
kind: Service
metadata:
  annotations:
    updated.by: Jason Verde
  creationTimestamp: null
  labels:
    purpose: mongodb
  name: mongodb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    purpose: mongodb
status:
  loadBalancer: {}
